#include <stdio.h>
#include "Utils.h"	// generated by javah

JNIEXPORT jint JNICALL Java_edu_Utils_arrayRegionImpl
  (JNIEnv * env, jclass claz, jbyteArray array) {
	jint i;
	for (i = 0; i < 3; i++) {
		printf("Hello \n");
	}
	return i;
}