/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_Utils */

#ifndef _Included_edu_Utils
#define _Included_edu_Utils
#ifdef __cplusplus
extern "C" {
#endif
#undef edu_Utils_SEED
#define edu_Utils_SEED -889275714L
/*
 * Class:     edu_Utils
 * Method:    arrayRegionImpl
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_edu_Utils_arrayRegionImpl
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     edu_Utils
 * Method:    arrayElementsImpl
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_edu_Utils_arrayElementsImpl
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     edu_Utils
 * Method:    arrayElementsCriticalImpl
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_edu_Utils_arrayElementsCriticalImpl
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     edu_Utils
 * Method:    javaCriticalImpl
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_edu_Utils_javaCriticalImpl
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
