/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_NativeUtils */

#ifndef _Included_edu_NativeUtils
#define _Included_edu_NativeUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_NativeUtils
 * Method:    cpuidrdtsc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_NativeUtils_cpuidrdtsc
  (JNIEnv *, jclass);

/*
 * Class:     edu_NativeUtils
 * Method:    rdtsc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_NativeUtils_rdtsc
  (JNIEnv *, jclass);

/*
 * Class:     edu_NativeUtils
 * Method:    rdtscp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_NativeUtils_rdtscp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
