/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_SysTime */

#ifndef _Included_edu_SysTime
#define _Included_edu_SysTime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_SysTime
 * Method:    cpuidrdtsc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_SysTime_cpuidrdtsc
  (JNIEnv *, jclass);

/*
 * Class:     edu_SysTime
 * Method:    rdtsc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_SysTime_rdtsc
  (JNIEnv *, jclass);

/*
 * Class:     edu_SysTime
 * Method:    rdtscp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_edu_SysTime_rdtscp
  (JNIEnv *, jclass);

/*
 * Class:     edu_SysTime
 * Method:    compress
 * Signature: ([I[B)I
 */
JNIEXPORT jint JNICALL Java_edu_SysTime_compress
  (JNIEnv *, jclass, jintArray, jbyteArray);

/*
 * Class:     edu_SysTime
 * Method:    compressCritical
 * Signature: ([I[B)I
 */
JNIEXPORT jint JNICALL Java_edu_SysTime_compressCritical
  (JNIEnv *, jclass, jintArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
